#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : golang-github-mitchellh-mapstructure
Version  : d2dd0262208475919e1a362f675cfc0e7c10e905
Release  : 1
URL      : https://github.com/mitchellh/mapstructure/archive/d2dd0262208475919e1a362f675cfc0e7c10e905.tar.gz
Source0  : https://github.com/mitchellh/mapstructure/archive/d2dd0262208475919e1a362f675cfc0e7c10e905.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : go

%description
# mapstructure
mapstructure is a Go library for decoding generic map values to structures
and vice versa, while providing helpful error handling.

%prep
%setup -q -n mapstructure-d2dd0262208475919e1a362f675cfc0e7c10e905

%build

%install
gopath="/usr/lib/golang"
library_path="github.com/mitchellh/mapstructure"
rm -rf %{buildroot}
install -d -p %{buildroot}${gopath}/src/${library_path}/
for file in $(find . -iname "*.go" -o -iname "*.h" -o -iname "*.c") ; do
     echo ${file}
     install -d -p %{buildroot}${gopath}/src/${library_path}/$(dirname $file)
     cp -pav $file %{buildroot}${gopath}/src/${library_path}/$file
done

%check
gopath="/usr/lib/golang"
export GOPATH="%{buildroot}${gopath}"
go test -v -x github.com/mitchellh/mapstructure

%files
%defattr(-,root,root,-)
/usr/lib/golang/src/github.com/mitchellh/mapstructure/decode_hooks.go
/usr/lib/golang/src/github.com/mitchellh/mapstructure/decode_hooks_test.go
/usr/lib/golang/src/github.com/mitchellh/mapstructure/error.go
/usr/lib/golang/src/github.com/mitchellh/mapstructure/mapstructure.go
/usr/lib/golang/src/github.com/mitchellh/mapstructure/mapstructure_benchmark_test.go
/usr/lib/golang/src/github.com/mitchellh/mapstructure/mapstructure_bugs_test.go
/usr/lib/golang/src/github.com/mitchellh/mapstructure/mapstructure_examples_test.go
/usr/lib/golang/src/github.com/mitchellh/mapstructure/mapstructure_test.go
